services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=85%
      - cluster.routing.allocation.disk.watermark.high=90%
      - cluster.routing.allocation.disk.watermark.flood_stage=95%
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk-network

  logstash:
    image: logstash:8.5.0
    container_name: logstash
    ports:
      - "5000:5000"
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /home/ubuntu/HomeSOC/logs:/home/ubuntu/HomeSOC/logs:ro
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  kibana:
    image: kibana:8.5.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS="--max-old-space-size=1024"
    depends_on:
      - elasticsearch
    networks:
      - elk-network

volumes:
  esdata:

networks:
  elk-network:
    driver: bridge
